language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

language: node_js
scripts:
  - npm install codecov -g
after_success:
  - codecov